/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePkg;

import DataPkg.SavedFileObj;
import DataPkg.frequencyFileReader;
import DataPkg.graphFileReader;
import DataPkg.posMeasuresFileReader;
import InterfacePkg.tools.baseKnowlegeFrame;
import InterfacePkg.tools.graphicBarFrame;
import InterfacePkg.tools.posMeasuresFrame;
import InterfacePkg.tools.frequencyMeasuresFrame;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ignacio
 */
public class MainMenuFrame extends javax.swing.JFrame {    
    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        BtnGroup.add(firstGradeRBtn);
        BtnGroup.add(secondGradeRBtn);
        BtnGroup.add(thirdGradeRBtn);
        BtnGroup.add(fourthGradeRBtn);
        BtnGroup.add(fifthGradeRBtn);
        BtnGroup.add(sixthGradeRBtn);
        BtnGroup.add(seventhGradeRBtn);
        BtnGroup.add(eigthGradeRBtn);
        BtnGroup.add(ninthGradeRBtn);
        BtnGroup.add(tenthGradeRBtn);
        BtnGroup.add(eleventhGradeRBtn);
        firstGradeRBtn.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemCB = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        firstGradeRBtn = new javax.swing.JRadioButton();
        secondGradeRBtn = new javax.swing.JRadioButton();
        thirdGradeRBtn = new javax.swing.JRadioButton();
        fourthGradeRBtn = new javax.swing.JRadioButton();
        fifthGradeRBtn = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        sixthGradeRBtn = new javax.swing.JRadioButton();
        seventhGradeRBtn = new javax.swing.JRadioButton();
        eigthGradeRBtn = new javax.swing.JRadioButton();
        ninthGradeRBtn = new javax.swing.JRadioButton();
        tenthGradeRBtn = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        eleventhGradeRBtn = new javax.swing.JRadioButton();
        closeBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadMBtn = new javax.swing.JMenuItem();
        toolMI = new javax.swing.JMenu();
        graphMakerMI = new javax.swing.JMenuItem();
        frequencyMBtn = new javax.swing.JMenuItem();
        posMeasuresMBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tutor Digital");

        jLabel2.setText("Estadistica y Probabilidad");

        itemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dato", "Interrogación", "Variabilidad" }));

        firstGradeRBtn.setText("Primero");
        firstGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstGradeRBtnMouseClicked(evt);
            }
        });

        secondGradeRBtn.setText("Segundo");
        secondGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondGradeRBtnMouseClicked(evt);
            }
        });

        thirdGradeRBtn.setText("Tercero");
        thirdGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdGradeRBtnMouseClicked(evt);
            }
        });

        fourthGradeRBtn.setText("Cuarto");
        fourthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourthGradeRBtnMouseClicked(evt);
            }
        });

        fifthGradeRBtn.setText("Quinto");
        fifthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fifthGradeRBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondGradeRBtn)
                    .addComponent(firstGradeRBtn)
                    .addComponent(fifthGradeRBtn)
                    .addComponent(thirdGradeRBtn)
                    .addComponent(fourthGradeRBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourthGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fifthGradeRBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sixthGradeRBtn.setText("Sexto");
        sixthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixthGradeRBtnMouseClicked(evt);
            }
        });

        seventhGradeRBtn.setText("Sétimo");
        seventhGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seventhGradeRBtnMouseClicked(evt);
            }
        });

        eigthGradeRBtn.setText("Octavo");
        eigthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eigthGradeRBtnMouseClicked(evt);
            }
        });

        ninthGradeRBtn.setText("Noveno");
        ninthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ninthGradeRBtnMouseClicked(evt);
            }
        });

        tenthGradeRBtn.setText("Décimo");
        tenthGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenthGradeRBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sixthGradeRBtn)
                    .addComponent(seventhGradeRBtn)
                    .addComponent(eigthGradeRBtn)
                    .addComponent(ninthGradeRBtn)
                    .addComponent(tenthGradeRBtn))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sixthGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seventhGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eigthGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ninthGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenthGradeRBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(130, 122));

        eleventhGradeRBtn.setText("Undécimo");
        eleventhGradeRBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleventhGradeRBtnMouseClicked(evt);
            }
        });

        closeBtn.setText("Cerrar");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        acceptBtn.setText("Aceptar");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eleventhGradeRBtn)
                    .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eleventhGradeRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptBtn)
                .addGap(18, 18, 18)
                .addComponent(closeBtn)
                .addGap(14, 14, 14))
        );

        jMenu1.setText("Archivo");

        loadMBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        loadMBtn.setText("Cargar");
        loadMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMBtnActionPerformed(evt);
            }
        });
        jMenu1.add(loadMBtn);

        jMenuBar1.add(jMenu1);

        toolMI.setText("Herramientas");

        graphMakerMI.setText("Graficador");
        graphMakerMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphMakerMIActionPerformed(evt);
            }
        });
        toolMI.add(graphMakerMI);

        frequencyMBtn.setText("Frecuencias");
        frequencyMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyMBtnActionPerformed(evt);
            }
        });
        toolMI.add(frequencyMBtn);

        posMeasuresMBtn.setText("Medidas de Posición");
        posMeasuresMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posMeasuresMBtnActionPerformed(evt);
            }
        });
        toolMI.add(posMeasuresMBtn);

        jMenuBar1.add(toolMI);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 338, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        if(firstGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Dato")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(10);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Interrogación")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(11);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Variabilidad")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(12);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(secondGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Dato")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(10);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Interrogación")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(11);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Variabilidad")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(20);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(thirdGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Interrogación")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(30);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(fourthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Madición")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(40);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(fifthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Gráfica")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(50);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Muestra")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(51);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(sixthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Frecuencia")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(60);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Porcentaje")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(61);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(seventhGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Característica")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(70);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Dato")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(71);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Frecuencia Absoluta")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(72);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Frecuencia Relativa")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(73);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Media Aritmética")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(74);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Muestra")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(75);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Variabilidad")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(76);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Variable")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(77);
                a.setVisible(true);
                this.dispose();
            }
        } 
        if(eigthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Diagrama")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(80);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Frecuencia Absoluta")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(81);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Gráfica")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(82);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Medidas de Posición")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(83);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Moda")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(84);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Recorrido")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(85);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(ninthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Dispersión")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(90);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Frecuencia Absoluta")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(91);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Gráfica")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(92);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Moda")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(93);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Recorrido")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(94);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(tenthGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Cuartiles")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(100);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Media Aritmética")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(101);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Media Aritmética Ponderada")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(102);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Mediana")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(103);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Moda")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(104);
                a.setVisible(true);
                this.dispose();
            }
        }
        if(eleventhGradeRBtn.isSelected()){
            if(itemCB.getSelectedItem().equals("Coeficiente de Variación")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(110);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Desviación Estándar")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(111);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Rango")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(112);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Rango Intercuartílico")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(113);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Variabilidad")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(114);
                a.setVisible(true);
                this.dispose();
            }
            if(itemCB.getSelectedItem().equals("Varianza")){
                baseKnowlegeFrame a =  new baseKnowlegeFrame(115);
                a.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /*First radio button menu changer
    All mouse clicked events for radio 
    buttons are the same for each subject*/
    private void firstGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Dato");
        itemCB.addItem("Interrogación");
        itemCB.addItem("Variabilidad");
    }//GEN-LAST:event_firstGradeRBtnMouseClicked

    private void secondGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Dato");
        itemCB.addItem("Interrogación");
        itemCB.addItem("Variabilidad");
    }//GEN-LAST:event_secondGradeRBtnMouseClicked

    private void thirdGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Interrogación");
    }//GEN-LAST:event_thirdGradeRBtnMouseClicked

    private void fourthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Medición");
    }//GEN-LAST:event_fourthGradeRBtnMouseClicked

    private void fifthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fifthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Gráfica");
        itemCB.addItem("Muestra");
    }//GEN-LAST:event_fifthGradeRBtnMouseClicked

    private void sixthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Frecuencia");
        itemCB.addItem("Porcentaje");
    }//GEN-LAST:event_sixthGradeRBtnMouseClicked

    private void seventhGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seventhGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Característica");
        itemCB.addItem("Dato");
        itemCB.addItem("Frecuecia Absoluta");
        itemCB.addItem("Frecuencia Relativa");
        itemCB.addItem("Media Aritmética");
        itemCB.addItem("Muestra");
        itemCB.addItem("Variabilidad");
        itemCB.addItem("Variable");
    }//GEN-LAST:event_seventhGradeRBtnMouseClicked

    private void eigthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eigthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Diagrama");
        itemCB.addItem("Frecuencia Absoluta");
        itemCB.addItem("Gráfica");
        itemCB.addItem("Medidas de Posición");
        itemCB.addItem("Moda");
        itemCB.addItem("Recorrido");        
    }//GEN-LAST:event_eigthGradeRBtnMouseClicked

    private void ninthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ninthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Dispersión");
        itemCB.addItem("Distribuciones de Frecuencia");
        itemCB.addItem("Gráfica");
        itemCB.addItem("Moda");
        itemCB.addItem("Recorrido");
    }//GEN-LAST:event_ninthGradeRBtnMouseClicked

    private void tenthGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenthGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Cuartiles");
        itemCB.addItem("Media Aritmética");
        itemCB.addItem("Media Aritmética Ponderada");
        itemCB.addItem("Mediana");
        itemCB.addItem("Moda");
    }//GEN-LAST:event_tenthGradeRBtnMouseClicked

    private void eleventhGradeRBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleventhGradeRBtnMouseClicked
        itemCB.removeAllItems();
        itemCB.addItem("Coeficiente de Variación");
        itemCB.addItem("Desviación Estándar");
        itemCB.addItem("Rango");
        itemCB.addItem("Rango Intercuartílico");
        itemCB.addItem("Variabilidad");
        itemCB.addItem("Varianza");
    }//GEN-LAST:event_eleventhGradeRBtnMouseClicked

    private void graphMakerMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphMakerMIActionPerformed
        graphicBarFrame a =  new graphicBarFrame(null,null);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_graphMakerMIActionPerformed

    private void frequencyMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyMBtnActionPerformed
        frequencyMeasuresFrame a =  new frequencyMeasuresFrame(null,null);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_frequencyMBtnActionPerformed

    private void loadMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("DSTF Files", "dstf");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Parts of the file manager(path, and savedFileObj)
            File file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            Path pathS = Paths.get(path);
            SavedFileObj e = null;
            
            //
            try{           
                FileInputStream fileIn = new FileInputStream(path);
                ObjectInputStream in = new ObjectInputStream(fileIn);
                e = (SavedFileObj) in.readObject();
                if(e.getWindowType() == 1){
                    graphFileReader a = (graphFileReader) in.readObject();
                    in.close();
                    fileIn.close();
                    graphicBarFrame b =  new graphicBarFrame(a,pathS.getFileName().toString());
                    b.setVisible(true);
                    this.dispose();
                }
                else if(e.getWindowType() == 2){
                    frequencyFileReader a = (frequencyFileReader) in.readObject();
                    in.close();
                    fileIn.close();
                    frequencyMeasuresFrame b = new frequencyMeasuresFrame(a, pathS.getFileName().toString());
                    b.setVisible(true);
                    this.dispose();
                }
                else if(e.getWindowType() == 3){
                    posMeasuresFileReader a = (posMeasuresFileReader) in.readObject();
                    in.close();
                    fileIn.close();
                    posMeasuresFrame b = new posMeasuresFrame(a, pathS.getFileName().toString());
                    b.setVisible(true);
                    this.dispose();
                }
                else{
                    in.close();
                    fileIn.close();
                }
            }
            catch(IOException i){
                i.printStackTrace();
            }
            catch(ClassNotFoundException c){
                c.printStackTrace();
            };
        }
    }//GEN-LAST:event_loadMBtnActionPerformed

    private void posMeasuresMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posMeasuresMBtnActionPerformed
        posMeasuresFrame a = new posMeasuresFrame(null,null);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_posMeasuresMBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JRadioButton eigthGradeRBtn;
    private javax.swing.JRadioButton eleventhGradeRBtn;
    private javax.swing.JRadioButton fifthGradeRBtn;
    private javax.swing.JRadioButton firstGradeRBtn;
    private javax.swing.JRadioButton fourthGradeRBtn;
    private javax.swing.JMenuItem frequencyMBtn;
    private javax.swing.JMenuItem graphMakerMI;
    private javax.swing.JComboBox<String> itemCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem loadMBtn;
    private javax.swing.JRadioButton ninthGradeRBtn;
    private javax.swing.JMenuItem posMeasuresMBtn;
    private javax.swing.JRadioButton secondGradeRBtn;
    private javax.swing.JRadioButton seventhGradeRBtn;
    private javax.swing.JRadioButton sixthGradeRBtn;
    private javax.swing.JRadioButton tenthGradeRBtn;
    private javax.swing.JRadioButton thirdGradeRBtn;
    private javax.swing.JMenu toolMI;
    // End of variables declaration//GEN-END:variables
}
